# Source: jxboot-helmfile-resources/templates/environments.yaml
apiVersion: jenkins.io/v1
kind: Environment
metadata:
  labels:
    env: "dev"
    team: jx
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: "dev"
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
spec:
  source:
    ref: "master"
    url: https://github.com/SSAKPAL1608/google_secret_manager.git
  kind: Development
  label: Development
  namespace: jx
  promotionStrategy: "Never"
  webHookEngine: "Lighthouse"
  teamSettings:
    appsRepository: https://jenkins-x-charts.github.io/repo
    defaultScheduler:
      apiVersion: jenkins.io/v1
      kind: Scheduler
      name: jx-meta-pipeline
    dockerRegistryOrg: "oci"
    envOrganisation: todo
    gitServer: https://github.com
    kubeProvider: "gke"
    pipelineUsername: "bot_token"
    pipelineUserEmail: "jenkins-x@googlegroups.com"
    prowConfig: Scheduler
    storageLocations:
    - bucketUrl: "gs://logs-tf-jx-adapted-tapir-fc5854c1005c"
      classifier: "logs"
    - bucketUrl: "gs://reports-tf-jx-adapted-tapir-fc5854c1005c"
      classifier: "reports"
    - bucketUrl: "gs://repository-tf-jx-adapted-tapir-fc5854c1005c"
      classifier: "repository"
